def MathOp():
  division = (3 / 2)
  floor_div = (3 //2)
  modulo = (3 % 2)
  powerto = (3**2)
  return(division, floor_div, modulo, powerto)
(division, floor_div, modulo, powerto) = MathOp()
print("Simple Division:")
print(division)
print("Floor Value:")
print(floor_div)
print("Modulus:")
print(modulo)
print("X raise to power Y:")
print(powerto)
